# Generated by Django 2.0.5 on 2018-06-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('pricepoint', models.IntegerField()),
                ('restname', models.CharField(max_length=30)),
                ('cuisine', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
