# Generated by Django 2.0.5 on 2018-06-05 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mustapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='picurl',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
