# Generated by Django 2.0.5 on 2018-06-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustapp', '0002_options_picurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='picurl',
        ),
        migrations.AddField(
            model_name='options',
            name='image',
            field=models.ImageField(blank=True, upload_to='items/%Y/%m/%d'),
        ),
    ]
