# Generated by Django 2.0.5 on 2018-06-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustapp', '0003_auto_20180605_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
