# Generated by Django 2.0.5 on 2018-06-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustapp', '0004_auto_20180605_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
