# Generated by Django 2.0.5 on 2018-06-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustapp', '0005_auto_20180605_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
