# Generated by Django 2.0.5 on 2018-06-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustapp', '0006_auto_20180605_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
